name: flake8 Lint

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v2.4.0
      - name: Set up Python environment
        uses: actions/setup-python@98f2ad02fd48d057ee3b4d4f66525b231c3e52b6 # v3.0.0
        with:
          python-version: "3.8"
      - name: flake8 Lint
        uses: py-actions/flake8@6b71483a8fe60d4cb967d3aa4ee56e5e52711d30 # v2
        with:
          ignore: "W503,W605"
          max-line-length: "100"
          path: "post-processing/"
